// Autogenerated from Pigeon (v21.2.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.aimanager.child

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeObservationFacts (
  val usageGranted: Boolean,
  val usageSupported: Boolean,
  val usageGrantStatus: String,
  val unlocked: Boolean,
  val television: Boolean,
  val profile: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeObservationFacts {
      val usageGranted = pigeonVar_list[0] as Boolean
      val usageSupported = pigeonVar_list[1] as Boolean
      val usageGrantStatus = pigeonVar_list[2] as String
      val unlocked = pigeonVar_list[3] as Boolean
      val television = pigeonVar_list[4] as Boolean
      val profile = pigeonVar_list[5] as String
      return NativeObservationFacts(usageGranted, usageSupported, usageGrantStatus, unlocked, television, profile)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      usageGranted,
      usageSupported,
      usageGrantStatus,
      unlocked,
      television,
      profile,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeObservedApplication (
  val packageName: String,
  val displayName: String,
  val profile: String,
  val signingDigests: List<String?>,
  val versionCode: Long,
  val systemApplication: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeObservedApplication {
      val packageName = pigeonVar_list[0] as String
      val displayName = pigeonVar_list[1] as String
      val profile = pigeonVar_list[2] as String
      val signingDigests = pigeonVar_list[3] as List<String?>
      val versionCode = pigeonVar_list[4].let { num -> if (num is Int) num.toLong() else num as Long }
      val systemApplication = pigeonVar_list[5] as Boolean
      return NativeObservedApplication(packageName, displayName, profile, signingDigests, versionCode, systemApplication)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      packageName,
      displayName,
      profile,
      signingDigests,
      versionCode,
      systemApplication,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeUsageEntry (
  val packageName: String,
  val displayName: String,
  val firstTimeStamp: Long,
  val lastTimeStamp: Long,
  val foregroundMillis: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeUsageEntry {
      val packageName = pigeonVar_list[0] as String
      val displayName = pigeonVar_list[1] as String
      val firstTimeStamp = pigeonVar_list[2].let { num -> if (num is Int) num.toLong() else num as Long }
      val lastTimeStamp = pigeonVar_list[3].let { num -> if (num is Int) num.toLong() else num as Long }
      val foregroundMillis = pigeonVar_list[4].let { num -> if (num is Int) num.toLong() else num as Long }
      return NativeUsageEntry(packageName, displayName, firstTimeStamp, lastTimeStamp, foregroundMillis)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      packageName,
      displayName,
      firstTimeStamp,
      lastTimeStamp,
      foregroundMillis,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeUsageSample (
  val queryStart: Long,
  val queryEnd: Long,
  val observedAt: Long,
  val timeZone: String,
  val profile: String,
  val applications: List<NativeUsageEntry?>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeUsageSample {
      val queryStart = pigeonVar_list[0].let { num -> if (num is Int) num.toLong() else num as Long }
      val queryEnd = pigeonVar_list[1].let { num -> if (num is Int) num.toLong() else num as Long }
      val observedAt = pigeonVar_list[2].let { num -> if (num is Int) num.toLong() else num as Long }
      val timeZone = pigeonVar_list[3] as String
      val profile = pigeonVar_list[4] as String
      val applications = pigeonVar_list[5] as List<NativeUsageEntry?>
      return NativeUsageSample(queryStart, queryEnd, observedAt, timeZone, profile, applications)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      queryStart,
      queryEnd,
      observedAt,
      timeZone,
      profile,
      applications,
    )
  }
}
private object ObservationApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeObservationFacts.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeObservedApplication.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeUsageEntry.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeUsageSample.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is NativeObservationFacts -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is NativeObservedApplication -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is NativeUsageEntry -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is NativeUsageSample -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface AndroidObservationApi {
  fun inspect(callback: (Result<NativeObservationFacts>) -> Unit)
  fun inventory(callback: (Result<List<NativeObservedApplication?>>) -> Unit)
  fun usage(queryStart: Long, queryEnd: Long, callback: (Result<NativeUsageSample>) -> Unit)
  fun openUsageSettings(callback: (Result<Unit>) -> Unit)

  companion object {
    /** The codec used by AndroidObservationApi. */
    val codec: MessageCodec<Any?> by lazy {
      ObservationApiPigeonCodec
    }
    /** Sets up an instance of `AndroidObservationApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: AndroidObservationApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.child.AndroidObservationApi.inspect$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.inspect{ result: Result<NativeObservationFacts> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.child.AndroidObservationApi.inventory$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.inventory{ result: Result<List<NativeObservedApplication?>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.child.AndroidObservationApi.usage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val queryStartArg = args[0].let { num -> if (num is Int) num.toLong() else num as Long }
            val queryEndArg = args[1].let { num -> if (num is Int) num.toLong() else num as Long }
            api.usage(queryStartArg, queryEndArg) { result: Result<NativeUsageSample> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.child.AndroidObservationApi.openUsageSettings$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.openUsageSettings{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
